// <auto-generated />
namespace Laborator8App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ValidTaskMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidTaskMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202101061658567_ValidTaskMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
